system:
    default:
        fieldtypes:
            ezxml:
                custom_tags:
                    - { path: "%kernel.root_dir%/../vendor/ezsystems/marketing-automation-bundle/Resources/views/xmltext/custom_tag.xsl" }
