services:
    ez_marketing_automation.tracker_listener:
        class: EzSystems\MarketingAutomationBundle\EventListener\TrackerListener
        factory_service: ez_marketing_automation.legacy_config_resolver_aware_factory
        factory_method: buildTrackerListener
        tags:
            - { name: kernel.event_subscriber }

    ez_marketing_automation.legacy_config_resolver_aware_factory:
        class: EzSystems\MarketingAutomationBundle\DependencyInjection\Factory\ConfigResolverAwareFactory
        arguments: [@ezpublish.config.resolver]

    ez_marketing_automation.ezxml.pre_converter.form_custom_tag:
        lazy: true
        class: EzSystems\MarketingAutomationBundle\eZ\XmlText\PreConverter
        factory_service: ez_marketing_automation.legacy_config_resolver_aware_factory
        factory_method: buildCustomTagConverter
        tags:
            - { name: ezpublish.ezxml.converter }
